-- 2. DAILY SUMMARY TABLE
CREATE TABLE IF NOT EXISTS historical_daily_summary (
    id TEXT PRIMARY KEY,
    date DATE NOT NULL,
    day TEXT,
    togo DECIMAL(10,2) DEFAULT 0,
    dine_in DECIMAL(10,2) DEFAULT 0,
    tax DECIMAL(10,2) DEFAULT 0,
    gross_sale DECIMAL(10,2) DEFAULT 0,
    gratuity DECIMAL(10,2) DEFAULT 0,
    coupon_subtract DECIMAL(10,2) DEFAULT 0,
    net_sale DECIMAL(10,2) DEFAULT 0,
    tip_cr DECIMAL(10,2) DEFAULT 0,
    tip_cash DECIMAL(10,2) DEFAULT 0,
    before_earned DECIMAL(10,2) DEFAULT 0,
    credt_total DECIMAL(10,2) DEFAULT 0,
    deposited DECIMAL(10,2) DEFAULT 0,
    cash DECIMAL(10,2) DEFAULT 0,
    sc_merch DECIMAL(10,2) DEFAULT 0,
    sc_owner DECIMAL(10,2) DEFAULT 0,
    daily_earned DECIMAL(10,2) DEFAULT 0,
    weekly_earned DECIMAL(10,2) DEFAULT 0,
    lunch DECIMAL(10,2) DEFAULT 0,
    day_1 TEXT,
    date_1 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_22 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_23 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_24 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_25 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_26 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_27 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_28 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_29 DECIMAL(10,2) DEFAULT 0,
    unnamed_column_30 DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);